name = "erling-nails"
main = "./dist/_worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "SESSION", id = "e8aecf58377e4840a6af1c9e30a13728", preview_id = "0f7f4b228aab4a40bfffaf921ffe5e04" }
] 