name = "erling-nails"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
pages_build_output_dir = "dist"

[build.upload]
format = "modules"
main = "./_worker.js"
dir = "dist"

[site]
bucket = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "e8aecf58377e4840a6af1c9e30a13728"
preview_id = "0f7f4b228aab4a40bfffaf921ffe5e04" 